services:
  secrets:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./example/input.txt:/servitor/secrets/input:ro
      - ./example/output:/servitor/secrets/output
      - ./src:/app/src:ro
    command: tail -f /dev/null
    stop_grace_period: 0s
  remote:
    image: nginx
    volumes:
      - ./example/db.kdbx:/usr/share/nginx/html/db.kdbx:ro
